[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gorbagana_blitz = "84qjAb4ZCqyy2tt3p12RWqJgGXzwBVEEGibhFFZ9dF7d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/harshsharma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
